language: r
sudo: required

# Packages from Bioconductor needed
bioc_required: true

env:
  global:
    - BIOC_USE_DEVEL="TRUE"

# Be strict when checking package
warnings_are_errors: true

# Package dependencies from CRAN
r_binary_packages:
  - RUnit
  - knitr
  - rmarkdown

# Package dependencies from Bioconductor
bioc_packages:
  - BiocGenerics
  - IRanges
  - BiocStyle
  - S4Vectors

# Package dependencies for codecov
r_github_packages:
  - jimhester/covr

after_success:
  - Rscript -e 'library(covr);codecov()'
