language: r
sudo: required

# Packages from Bioconductor needed
bioc_required: true

# Be strict when checking package
warnings_are_errors: true

# Package dependencies from CRAN
r_binary_packages:
  - graphics
  - stats
  - RUnit
  - knitr

# Package dependencies from Bioconductor
bioc_packages:
  - BiocGenerics
  - IRanges
  - BiocStyle
  - S4Vectors

